Enhance main analysis script to print the number and names of loaded FCS files along with their channels
kiel@localhost ~/stage/flow/LST_Depletion_Analysis/02_scripts $ Rscript 00-main-analysis.R
As part of improvements to flowWorkspace, some behavior of
GatingSet objects has changed. For details, please read the section
titled "The cytoframe and cytoset classes" in the package vignette:

  vignette("flowWorkspace-Introduction", "flowWorkspace")
Loading required package: ggplot2
Loading required package: ncdfFlow
Loading required package: BH
── Attaching core tidyverse packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.3.0
✔ purrr     1.1.0     ✔ tidyr     1.3.1
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ ggcyto::%+%()   masks ggplot2::%+%()
✖ dplyr::filter() masks ncdfFlow::filter(), flowCore::filter(), stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
There were 50 or more warnings (use warnings() to see the first 50)
Number of FCS files loaded: 8
Loaded FCS files:
File 1: ../01_data/fcs//Spleenocytes_Tcells_FMO- no CD4 staining_002.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 2: ../01_data/fcs//Spleenocytes_Tcells_Rag2KO_005.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 3: ../01_data/fcs//Spleenocytes_Tcells_Unstained_control_001.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 4: ../01_data/fcs//Spleenocytes_Tcells_Vaccinated_GK15_006.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 5: ../01_data/fcs//Spleenocytes_Tcells_Vaccinated_GK15__2_007.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 6: ../01_data/fcs//Spleenocytes_Tcells_Vaccinated_GK15__3_009.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 7: ../01_data/fcs//Spleenocytes_Tcells_Vaccinated_Saline_004.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
File 8: ../01_data/fcs//Spleenocytes_Tcells_Vaccinated_aCD8_003.fcs
Channels:
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, $P11S, NA, $P13S, NA, $P15S, $P16S, NA, $P18S, NA
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1]  7  8  9 10
done!
Saving 7 x 7 in image
Saving 7 x 7 in image
Saving 7 x 7 in image
Error: CD4+CD8- not found!
Execution halted